name: Auto Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Run Tests
        run: |
          python find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt
          diff -u test_data/test1_expected.txt test_data/test1_actual.txt
          python find_lowest_number.py test_data/test2_input.txt test_data/test2_actual.txt
          diff -u test_data/test2_expected.txt test_data/test2_actual.txt
          if [ -s "test_data/test3_input.txt" ]; then
            python find_lowest_number.py test_data/test3_input.txt test_data/test3_actual.txt
            cmp -s test_data/test3_expected.txt test_data/test3_actual.txt || exit 1
          else
            echo "No numbers found in file" > test_data/test3_actual.txt
            cmp -s test_data/test3_expected.txt test_data/test3_actual.txt || exit 1
          fi
